THE FOLLOWING CODE PLOTS THE AGE DIFFERENCE IN THE LEAD CAST OF MEN AND WOMEN OVER THE DECADE.

STEP1:

MODULE IMPORTING

If you have error in dowloading the iplotly

$ pip install plotly==5.14.1

In [1]:
#importing modules for plotting 
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.io as pio

In [2]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
!ls "/content/drive"

MyDrive  Shareddrives

STEP 2:

PULLING DATA FROM CREATED DATA FILES AND SHOWING SAMPLES

In [4]:
#creating actresses dataframe
actresses_df = pd.read_csv('/content/drive/My Drive/actresses_df.cvs', sep=',')
actresses_df

,Unnamed: 0,tconst,nconst,category,primaryName,birthYear,primaryProfession,startYear
0,0,tt1921329,nm0503083,actress,Leonora,\N,actress,2011
1,1,tt1921329,nm2053650,actress,Rachel Shenton,\N,"actress,producer,writer",2011
2,2,tt1921329,nm2884061,actress,Lara de-Leuw,\N,actress,2011
3,3,tt2790166,nm0293415,actress,Helen Freeman,1886,actress,2013
4,4,tt2790166,nm5740482,actress,Olivia Knight,\N,"director,actress,writer",2013
...,...,...,...,...,...,...,...,...
5944274,5944274,tt9914552,nm10715664,actress,Yulya Betiyeva Budak,\N,NaN,2019
5944275,5944275,tt9914782,nm10537536,actress,Mirella Sessa,\N,actress,2018
5944276,5944276,tt9915160,nm10537836,actress,Pan Zhi Lin,\N,actress,2018
5944277,5944277,tt9916460,nm10538444,actress,Christina Tafralidou,\N,actress,2019
5944278,5944278,tt9916698,nm10004115,actress,Katerina Giannouli,\N,actress,2019

In [5]:
#creating actors dataframe
actor_df = pd.read_csv('/content/drive/My Drive/actors.cvs' , sep=',')
actor_df

,Unnamed: 0,tconst,nconst,category,primaryName,birthYear,primaryProfession,startYear
0,0,tt0427588,nm0278321,actor,Antonio Fino,\N,actor,2003
1,1,tt0427588,nm1759416,actor,Ernesto Pasquariello,\N,actor,2003
2,2,tt0427588,nm1758756,actor,Giuseppe Catillo,\N,actor,2003
3,3,tt0427588,nm0162571,actor,Vittorio Ciorcalo,1949,actor,2003
4,4,tt0427588,nm1758927,actor,Giuseppe Ferrigno,\N,actor,2003
...,...,...,...,...,...,...,...,...
7569896,7569896,tt9916746,nm10538626,actor,Dennis Papineau,\N,actor,2012
7569897,7569897,tt9916746,nm10538628,actor,Derek Parker,\N,actor,2012
7569898,7569898,tt9916746,nm10538627,actor,Ryan Torrence,\N,actor,2012
7569899,7569899,tt9916746,nm10538629,actor,Lloyd Valley,\N,actor,2012
7569900,7569900,tt9916856,nm10538646,actor,Andreas Demmel,\N,NaN,2015

STEP 3:

INPUT PARSING

In [10]:
#input parsing
x = input("name of actor? (Case sensetive)")
find = actor_df[actor_df["primaryName"] == x]
if find.empty:
    print("Actor not in dataset.")
else:
  tot = find['tconst']
  actresses_df_new = actresses_df[actresses_df['tconst'].isin(tot)].copy()

name of actor? (Case sensetive)Amitabh Bachchan

STEP 4:

AGE CALCULATION AND NaN EDGE CASE HANDLING

In [11]:
#dataframe mainpulation
unique_actresses_df = actresses_df_new.drop_duplicates(subset=["nconst", "primaryName", "birthYear", "primaryProfession"])
unique_actresses_df = unique_actresses_df.replace("\\N", pd.NA).fillna(method='ffill')

#age calculation
actor_age = pd.to_numeric(find["birthYear"].replace("\\N", pd.NA)).iloc[0]

#nan values edge case handling
if np.isnan(actor_age):
    print("actor age not found, please try again")
    actor_age = 0

In [12]:
actor_age

1942

In [13]:
#plotting age of actresses with respect to age of actors
fig = go.Figure(go.Scatter(x=unique_actresses_df["primaryName"], y=  actor_age - pd.to_numeric(unique_actresses_df["birthYear"], errors='coerce')))
fig.show()